import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-dashboard',
  template: `
    <ui-page title="Dashboard">
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>Aaron</ui-text>
      <ui-text>NEBBS</ui-text>
    </ui-page>
  `,
  styleUrls: ['./dashboard.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DashboardComponent {}
